# Generated by Django 5.1.15 on 2026-10-04 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_joining_date'),
        ('organization', '0002_alter_role_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('deadline', models.DateField()),
                ('duration_hours', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'Aadhaar / National ID'), ('PAN', 'PAN Card'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Degrees & Certificates'), ('EXPERIENCE', 'Experience & Relieving Letters'), ('OFFER_LETTER', 'Signed Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('NDA', 'Signed Non-Disclosure Agreement'), ('POLICY_AGREEMENT', 'Employee Handbook & Policy Signoff'), ('OTHER', 'Other Verified Document')], default='ID_PROOF', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified 🟢'), ('PENDING', 'Pending Verification 🟠'), ('EXPIRED', 'Expired / Needs Renewal 🔴'), ('MISSING', 'Missing ⚠️')], db_index=True, default='PENDING', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='employees.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='HRAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('EVENT', 'Company Event'), ('HOLIDAY', 'Holiday Notice'), ('GENERAL', 'General Announcement'), ('MILESTONE', 'Company Milestone / Celebration')], default='EVENT', max_length=20)),
                ('content', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LEAVE', 'Leave & Time Off Policy'), ('ATTENDANCE', 'Attendance & Punctuality Policy'), ('WFH', 'Work From Home / Remote Work Policy'), ('CODE_OF_CONDUCT', 'Employee Code of Conduct'), ('SECURITY', 'IT, Cyber Security & Device Usage'), ('TRAVEL_EXPENSE', 'Travel & Expense Reimbursement'), ('POSH', 'POSH & Workplace Safety Policy'), ('HANDBOOK', 'General Employee Handbook')], default='LEAVE', max_length=32)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('content', models.TextField()),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('ATTENDANCE_CORRECTION', 'Attendance Correction'), ('LEAVE', 'Leave Request'), ('DOC_UPDATE', 'Document / ID Update'), ('ADDRESS_UPDATE', 'Address / Contact Update'), ('BANK_UPDATE', 'Bank Details Update'), ('EMPLOYMENT_LETTER', 'Employment Verification Letter'), ('EXPERIENCE_LETTER', 'Experience / Service Letter'), ('SALARY_QUERY', 'Salary / Compensation Inquiry'), ('TRANSFER', 'Department Transfer'), ('PROMOTION', 'Promotion Consideration'), ('RESIGNATION', 'Resignation / Exit Notice'), ('ASSET_REQUEST', 'Device / ID Card Re-issue'), ('GRIEVANCE', 'HR Confidential Grievance')], default='ATTENDANCE_CORRECTION', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('HR_REVIEW', 'Under HR Review'), ('MANAGER_REVIEW', 'Under Manager Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed / Fulfilled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('location', models.CharField(default='Kanpur Headquarters / Hybrid', max_length=150)),
                ('openings_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open & Active'), ('ON_HOLD', 'On Hold'), ('FILLED', 'Filled'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('experience_required', models.CharField(default='1-3 Years', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='organization.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied / New'), ('SCREENING', 'Resume Screening'), ('INTERVIEW', 'Interview Scheduled'), ('SELECTED', 'Selected for Offer'), ('OFFER', 'Offer Rolled Out'), ('JOINED', 'Offer Accepted / Joined'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=20)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expected_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.jobopening')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('resignation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('last_working_day', models.DateField()),
                ('notice_period_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('RESIGNED', 'Resignation Submitted'), ('NOTICE_PERIOD', 'Serving Notice Period'), ('CLEARANCE_PENDING', 'Department Clearance Pending'), ('FNF_COMPLETED', 'Full & Final Settled'), ('EXITED', 'Formal Exit Complete')], db_index=True, default='RESIGNED', max_length=20)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('checklist_data', models.JSONField(default=dict)),
                ('exit_interview_notes', models.TextField(blank=True, null=True)),
                ('experience_letter_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_record', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personal_verified', models.BooleanField(default=False)),
                ('employment_details_set', models.BooleanField(default=False)),
                ('documents_uploaded', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('account_created', models.BooleanField(default=False)),
                ('assets_assigned', models.BooleanField(default=False)),
                ('training_assigned', models.BooleanField(default=False)),
                ('manager_assigned', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('cycle_name', models.CharField(default='Annual Appraisal 2026', max_length=100)),
                ('status', models.CharField(choices=[('GOAL_SETTING', 'Goal Setting'), ('MID_YEAR', 'Mid-Year Review'), ('MANAGER_REVIEW', 'Manager Review'), ('EMPLOYEE_FEEDBACK', 'Employee Feedback'), ('FINAL_REVIEW', 'Final HR Review'), ('COMPLETED', 'Completed')], db_index=True, default='MANAGER_REVIEW', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('kpi_score', models.IntegerField(default=85)),
                ('competencies_score', models.IntegerField(default=80)),
                ('manager_feedback', models.TextField(blank=True, null=True)),
                ('employee_self_review', models.TextField(blank=True, null=True)),
                ('development_areas', models.TextField(blank=True, null=True)),
                ('goals_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('onboardings_count', models.IntegerField(default=0)),
                ('leaves_processed_count', models.IntegerField(default=0)),
                ('corrections_approved_count', models.IntegerField(default=0)),
                ('candidates_interviewed_count', models.IntegerField(default=0)),
                ('documents_verified_count', models.IntegerField(default=0)),
                ('requests_resolved_count', models.IntegerField(default=0)),
                ('summary_notes', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('tomorrow_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed by HR Manager')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('executive', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='hr.hrpolicy')),
            ],
            options={
                'unique_together': {('policy', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned / Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Overdue / Expired')], db_index=True, default='ASSIGNED', max_length=20)),
                ('score_percentage', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='employees.employee')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='hr.trainingprogram')),
            ],
            options={
                'unique_together': {('program', 'employee')},
            },
        ),
    ]
