# Generated by Django 5.1.15 on 2026-10-03 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('attendance_date', models.DateField(db_index=True, verbose_name='Attendance Date')),
                ('server_check_in_time', models.TimeField(blank=True, null=True, verbose_name='Authoritative Server Check-in Time')),
                ('server_check_out_time', models.TimeField(blank=True, null=True, verbose_name='Authoritative Server Check-out Time')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late Arrival'), ('ON_LEAVE', 'On Leave'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20, verbose_name='Attendance Status')),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Check-in IP Address')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Check-out IP Address')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Check-in Latitude')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Check-in Longitude')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Check-out Latitude')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Check-out Longitude')),
                ('notes', models.TextField(blank=True, verbose_name='Attendance Notes / Remarks')),
                ('is_corrected', models.BooleanField(default=False, verbose_name='Is Manually Corrected')),
                ('check_in_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_attendances', to='accounts.userdevice')),
                ('check_out_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_attendances', to='accounts.userdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_date', '-server_check_in_time'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('requested_check_in_time', models.TimeField(blank=True, null=True, verbose_name='Requested Check-in Time')),
                ('requested_check_out_time', models.TimeField(blank=True, null=True, verbose_name='Requested Check-out Time')),
                ('requested_status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late Arrival'), ('ON_LEAVE', 'On Leave'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20, verbose_name='Requested Status')),
                ('reason', models.TextField(verbose_name='Reason for Correction')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Correction Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_remarks', models.TextField(blank=True, verbose_name='Manager/Admin Review Remarks')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendance', verbose_name='Attendance Record')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='employees.employee', verbose_name='Employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Attendance Correction',
                'verbose_name_plural': 'Attendance Corrections',
                'ordering': ['-created_at'],
            },
        ),
    ]
