# Generated by Django 5.1.15 on 2026-10-03 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'New Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DEADLINE', 'Task Deadline Approaching'), ('TASK_OVERDUE', 'Task Overdue'), ('TASK_BLOCKED', 'Task Blocked - Action Required'), ('TASK_SUBMITTED', 'Task Submitted for Review'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Changes Requested'), ('REPORT_REMINDER', 'Daily Work Report Reminder'), ('REPORT_SUBMITTED', 'Daily Work Report Submitted'), ('REPORT_CHANGES_REQUESTED', 'Report Changes Requested'), ('REPORT_APPROVED', 'Daily Work Report Approved'), ('SYSTEM_ALERT', 'System Security Alert')], default='TASK_ASSIGNED', max_length=40, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('link_type', models.CharField(blank=True, help_text='e.g. TASK, REPORT, SECURITY', max_length=50, null=True, verbose_name='Link Type')),
                ('link_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
