# Generated by Django 5.1.15 on 2026-10-04 13:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_phone', models.CharField(max_length=32)),
                ('partner_type', models.CharField(choices=[('banquet', 'Banquet / Venue'), ('cafe', 'Cafe / Lounge'), ('resort', 'Resort / Hotel'), ('caterer', 'Catering Partner'), ('decorator', 'Decoration Specialist'), ('logistics', 'Logistics Partner'), ('other', 'Other Partner')], default='banquet', max_length=32)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding / Reception'), ('corporate_event', 'Corporate Event'), ('birthday_party', 'Birthday / Social'), ('live_music', 'Live Music / Night'), ('seminar', 'Conference / Seminar'), ('catering_order', 'Bulk Catering Order'), ('banquet_booking', 'Banquet Booking'), ('other', 'Custom Event')], default='banquet_booking', max_length=32)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time_slot', models.CharField(default='10:00 AM - 04:00 PM', max_length=100)),
                ('guest_count', models.IntegerField(default=50)),
                ('package_name', models.CharField(default='Standard Executive Service', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid (Deposit Received)'), ('PENDING', 'Payment Pending'), ('REFUNDED', 'Refund Processed')], default='PARTIAL', max_length=32)),
                ('partner_confirmation_status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Partner Confirmed'), ('REJECTED', 'Partner Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='CONFIRMED', max_length=32)),
                ('operations_status', models.CharField(choices=[('PREPARATION_PENDING', 'Preparation Pending'), ('COORDINATION', 'In Coordination'), ('READINESS_CHECK', 'Readiness Inspection'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Service Ready'), ('EXECUTING', 'Currently Live / Executing'), ('COMPLETED', 'Completed & Verified'), ('ISSUE_REPORTED', 'Issue Reported / Delayed'), ('CANCELLED', 'Cancelled')], db_index=True, default='COORDINATION', max_length=32)),
                ('readiness_percentage', models.IntegerField(default=0)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('venue_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations_bookings', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_operations_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReadinessChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hall_confirmed', models.BooleanField(default=False)),
                ('seating_confirmed', models.BooleanField(default=False)),
                ('decoration_confirmed', models.BooleanField(default=False)),
                ('catering_confirmed', models.BooleanField(default=False)),
                ('parking_confirmed', models.BooleanField(default=False)),
                ('setup_confirmed', models.BooleanField(default=False)),
                ('staff_confirmed', models.BooleanField(default=False)),
                ('power_backup_confirmed', models.BooleanField(default=False)),
                ('score_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_checklist', to='operations.bookingoperation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AUDIO_VISUAL', 'Audio / Visual Equipment'), ('POS_DEVICE', 'POS Terminal & Scanner'), ('FURNITURE', 'Event Furniture & Staging'), ('DECOR_PROP', 'Decorative Props & Lighting'), ('UNIFORM', 'Operations Uniforms & Badges'), ('SAFETY_EQUIPMENT', 'Safety & First Aid Kit'), ('LOGISTICS', 'Logistics & Trolleys')], default='AUDIO_VISUAL', max_length=32)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available in Warehouse'), ('ASSIGNED', 'Assigned to Event'), ('IN_USE', 'Currently in Live Use'), ('RETURNED', 'Returned Pending Check'), ('MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged / Write-off')], db_index=True, default='AVAILABLE', max_length=32)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('NEEDS_REPAIR', 'Needs Repair')], default='EXCELLENT', max_length=32)),
                ('location', models.CharField(default='Central Operations Warehouse', max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('last_inspected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operational_assets', to=settings.AUTH_USER_MODEL)),
                ('current_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.bookingoperation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationsIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('PARTNER_DELAY', 'Partner Response Delay'), ('VENUE_DEFECT', 'Venue Physical Defect / Missing Amenity'), ('PAYMENT_DISPUTE', 'Payment / Invoice Dispute'), ('CUSTOMER_COMPLAINT', 'Customer Service Complaint'), ('CATERING_QUALITY', 'Catering / Food Quality Issue'), ('DECORATION_MISMATCH', 'Decoration / Theme Mismatch'), ('STAFF_SHORTAGE', 'Operations Staff Shortage'), ('LOGISTICS_DELAY', 'Logistics / Transport Delay'), ('EQUIPMENT_FAILURE', 'Equipment / AV Failure'), ('OTHER', 'Other Operational Issue')], default='PARTNER_DELAY', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Blocker')], default='HIGH', max_length=20)),
                ('problem_statement', models.TextField()),
                ('sla_hours', models.IntegerField(default=2)),
                ('sla_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated to Management'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('escalation_level', models.CharField(choices=[('EXECUTIVE', 'Operations Executive'), ('MANAGER', 'Operations Manager'), ('ADMIN', 'Executive Management / Admin')], default='EXECUTIVE', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations_issues', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_issues', to='operations.bookingoperation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_operations_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'sla_deadline'],
            },
        ),
        migrations.CreateModel(
            name='OperationsRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('ADDITIONAL_STAFF', 'Additional Operations Staff'), ('EQUIPMENT_REQUISITION', 'Equipment / Asset Requisition'), ('BUDGET_APPROVAL', 'Emergency Expense / Budget Approval'), ('TIMELINE_EXTENSION', 'Service Timeline Extension'), ('PARTNER_REPLACEMENT', 'Emergency Partner Replacement'), ('REFUND_OVERRIDE', 'Customer Refund / Discount Override'), ('TRANSPORT_SUPPORT', 'Logistics / Transport Vehicle Support')], default='ADDITIONAL_STAFF', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('NEW', 'New Request'), ('REVIEW', 'Under Review'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Fulfilled & Completed')], db_index=True, default='NEW', max_length=32)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('PASS', 'Pass / Approved'), ('PASS_WITH_ISSUES', 'Pass with Minor Flags'), ('FAIL', 'Failed / Non-Compliant')], default='PASS', max_length=32)),
                ('score', models.IntegerField(default=100)),
                ('checklist_data', models.JSONField(default=dict)),
                ('photos', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_generated_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.operationsissue')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='operations.bookingoperation')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('tasks_completed_count', models.IntegerField(default=0)),
                ('bookings_handled_count', models.IntegerField(default=0)),
                ('issues_resolved_count', models.IntegerField(default=0)),
                ('followups_count', models.IntegerField(default=0)),
                ('visits_count', models.IntegerField(default=0)),
                ('quality_checks_count', models.IntegerField(default=0)),
                ('summary_notes', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('tomorrow_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed by Manager')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('executive', 'report_date')},
            },
        ),
    ]
