# Generated by Django 5.1.15 on 2026-10-04 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('event_type', models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_ACTIVATED', 'Employee Activated'), ('EMPLOYEE_RESIGNED', 'Employee Resigned'), ('EMPLOYEE_EXITED', 'Employee Exited'), ('PARTNER_CREATED', 'Partner Created'), ('PARTNER_KYC_SUBMITTED', 'Partner KYC Submitted'), ('PARTNER_APPROVED', 'Partner Approved by Admin'), ('PARTNER_ACTIVATED', 'Partner Activated across Ops & Accounts'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('EVENT_COMPLETED', 'Event Completed'), ('ISSUE_REPORTED', 'Operations Issue Reported'), ('TICKET_CREATED', 'IT Ticket Created'), ('TICKET_RESOLVED', 'IT Ticket Resolved'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('EXPENSE_REQUESTED', 'Expense Requested'), ('EXPENSE_APPROVED', 'Expense Approved'), ('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_BLOCKED', 'Task Blocked'), ('TASK_ESCALATED', 'Task Escalated'), ('WORKFLOW_STARTED', 'Workflow Started'), ('WORKFLOW_STEP_COMPLETED', 'Workflow Step Completed'), ('WORKFLOW_COMPLETED', 'Workflow Completed')], db_index=True, max_length=60, verbose_name='Event Type')),
                ('entity_type', models.CharField(db_index=True, max_length=50, verbose_name='Entity Type')),
                ('entity_id', models.CharField(db_index=True, max_length=100, verbose_name='Entity Reference ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Event Payload')),
                ('processed', models.BooleanField(default=True, verbose_name='Processed by Engine')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_central_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Central Event Record',
                'verbose_name_plural': 'Central Event Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterWorkflowProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('process_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Workflow Reference Code')),
                ('title', models.CharField(max_length=255, verbose_name='Workflow Title')),
                ('workflow_type', models.CharField(choices=[('EMPLOYEE_ONBOARDING', 'Employee Onboarding (HR + IT + Manager + Admin)'), ('PARTNER_ONBOARDING', 'PartyBala Partner Pipeline (Marketing + Admin + Operations + Accounts)'), ('BOOKING_OPERATIONS', 'Booking & Event Execution (Operations + Accounts + Marketing)'), ('IT_INCIDENT', 'IT Incident & Resolution (Operations + IT + DevOps)'), ('LEAVE_REQUEST', 'Employee Leave (Employee + Manager + HR + Attendance)'), ('EXPENSE_PURCHASE', 'Purchase & Expense Approval (Employee + Manager + Dept Head + Accounts)'), ('EMPLOYEE_EXIT', 'Employee Offboarding (Manager + HR + IT + Accounts)'), ('CUSTOM', 'Custom Organization Workflow')], db_index=True, max_length=50, verbose_name='Workflow Type')),
                ('entity_type', models.CharField(db_index=True, max_length=50, verbose_name='Linked Entity Type')),
                ('entity_id', models.CharField(db_index=True, max_length=100, verbose_name='Linked Entity ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting on External / Dependency'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], db_index=True, default='IN_PROGRESS', max_length=30, verbose_name='Status')),
                ('current_stage_name', models.CharField(max_length=150, verbose_name='Current Stage Name')),
                ('current_department', models.CharField(db_index=True, max_length=100, verbose_name='Current Responsible Department')),
                ('current_role', models.CharField(max_length=100, verbose_name='Current Responsible Role')),
                ('sla_hours', models.IntegerField(default=24, verbose_name='Total SLA Hours')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='SLA Target Deadline')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Is Escalated')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Workflow Progress %')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Workflow Metadata & State')),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Current Assignee')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Initiator')),
            ],
            options={
                'verbose_name': 'Master Workflow Process',
                'verbose_name_plural': 'Master Workflow Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('step_order', models.PositiveIntegerField(default=1, verbose_name='Step Order Index')),
                ('title', models.CharField(max_length=200, verbose_name='Step Title')),
                ('description', models.TextField(blank=True, verbose_name='Step Instructions')),
                ('department', models.CharField(max_length=100, verbose_name='Target Department')),
                ('responsible_role', models.CharField(max_length=100, verbose_name='Responsible Role')),
                ('action_type', models.CharField(choices=[('TASK_EXECUTION', 'Task Execution'), ('APPROVAL', 'Manager/Admin Approval'), ('DOCUMENT_VERIFICATION', 'Document Verification / KYC'), ('SYSTEM_PROVISIONING', 'System Access & Device Provisioning'), ('COMMERCIAL_SETUP', 'Banking & Commercial Configuration'), ('QUALITY_AUDIT', 'Service Readiness Inspection'), ('HANDOVER', 'Formal Handover & Knowledge Transfer')], default='TASK_EXECUTION', max_length=50, verbose_name='Action Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30, verbose_name='Status')),
                ('sla_hours', models.IntegerField(default=8, verbose_name='Step SLA Hours')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Step Due Date')),
                ('linked_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linked Task ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('comments', models.TextField(blank=True, verbose_name='Outcome Notes / Rejection Reason')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.masterworkflowprocess', verbose_name='Parent Process')),
            ],
            options={
                'verbose_name': 'Master Workflow Step',
                'verbose_name_plural': 'Master Workflow Steps',
                'ordering': ['step_order'],
                'unique_together': {('process', 'step_order')},
            },
        ),
    ]
