# Generated by Django 5.1.15 on 2026-10-03 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'User Login Successful'), ('AUTH_LOGIN_FAILED', 'User Login Failed'), ('AUTH_MFA_FAILED', 'MFA Verification Failed'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQ', 'Password Reset Requested'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Profile Updated'), ('EMPLOYEE_STATUS_CHANGED', 'Employee Status Changed'), ('POSITION_CHANGED', 'Employee Position Changed'), ('ROLE_CHANGED', 'Employee Role Changed'), ('PERMISSION_CHANGED', 'Role Permissions Changed'), ('ATTENDANCE_CHECKIN', 'Attendance Check-In'), ('ATTENDANCE_CHECKOUT', 'Attendance Check-Out'), ('ATTENDANCE_CORRECTION_REQ', 'Attendance Correction Requested'), ('ATTENDANCE_CORRECTION_APPROVED', 'Attendance Correction Approved'), ('ATTENDANCE_CORRECTION_REJECTED', 'Attendance Correction Rejected'), ('DEVICE_REVOKED', 'Device Revoked'), ('SESSION_REVOKED', 'Session Revoked'), ('ADMIN_ACTION', 'Administrative Override')], db_index=True, max_length=60, verbose_name='Event Type')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Target Model')),
                ('target_id', models.CharField(blank=True, max_length=255, verbose_name='Target ID / Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Event Metadata / Diff')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
