# Generated by Django 5.1.15 on 2026-10-03 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('plan_date', models.DateField(db_index=True, verbose_name='Plan Date')),
                ('planned_items', models.JSONField(default=list, help_text='List of goal items', verbose_name='Planned Tasks / Goals')),
                ('is_started', models.BooleanField(default=False, verbose_name='Day Started')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('notes', models.TextField(blank=True, verbose_name='Plan Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Daily Work Plan',
                'verbose_name_plural': 'Daily Work Plans',
                'ordering': ['-plan_date'],
                'unique_together': {('employee', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('report_date', models.DateField(db_index=True, verbose_name='Report Date')),
                ('summary_text', models.TextField(verbose_name="Summary of Day's Work")),
                ('completed_summary', models.TextField(blank=True, verbose_name='Completed Work Highlights')),
                ('pending_summary', models.TextField(blank=True, verbose_name='Pending Items')),
                ('blocked_summary', models.TextField(blank=True, verbose_name='Blockers / Issues Encountered')),
                ('tomorrow_plan', models.TextField(blank=True, verbose_name="Tomorrow's Plan")),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted (Awaiting Review)'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=25, verbose_name='Report Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('manager_remarks', models.TextField(blank=True, verbose_name='Manager Remarks / Feedback')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='employees.employee', verbose_name='Employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Daily Work Report',
                'verbose_name_plural': 'Daily Work Reports',
                'ordering': ['-report_date'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
    ]
