# Generated by Django 5.1.15 on 2026-10-04 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0002_alter_role_code'),
        ('tasks', '0002_task_actual_hours_task_department_data_and_more'),
        ('work_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('title', models.CharField(max_length=200, verbose_name='Announcement Title')),
                ('content', models.TextField(verbose_name='Announcement Body')),
                ('target_type', models.CharField(choices=[('ALL', 'Entire Company'), ('DEPARTMENT', 'Department Specific'), ('POSITION', 'Position Specific')], default='ALL', max_length=20, verbose_name='Target Audience')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent Broadcast')], default='NORMAL', max_length=20, verbose_name='Priority')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned to Top')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='organization.department')),
            ],
            options={
                'verbose_name': 'Company Announcement',
                'verbose_name_plural': 'Company Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Log Timestamp')),
                ('activity_text', models.CharField(max_length=255, verbose_name='Activity Description')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (Minutes)')),
                ('category', models.CharField(default='DEVELOPMENT', max_length=50, verbose_name='Activity Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_diary_entries', to='employees.employee', verbose_name='Employee')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='tasks.task', verbose_name='Related Task')),
            ],
            options={
                'verbose_name': 'Work Diary Entry',
                'verbose_name_plural': 'Work Diary Entries',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStandup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('standup_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Standup Date')),
                ('yesterday_completed', models.TextField(verbose_name='What did you complete yesterday?')),
                ('today_planned', models.TextField(verbose_name='What will you work on today?')),
                ('blockers_encountered', models.TextField(blank=True, verbose_name='Any blockers or help needed?')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_feedback', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_standups', to='employees.employee', verbose_name='Employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_standups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Standup',
                'verbose_name_plural': 'Daily Standups',
                'ordering': ['-standup_date', '-submitted_at'],
                'unique_together': {('employee', 'standup_date')},
            },
        ),
    ]
