# Generated by Django 5.1.15 on 2026-10-05 14:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_joining_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Unique Device Identifier')),
                ('device_name', models.CharField(blank=True, max_length=150, verbose_name='Device Name')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='Device Hardware Model')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='OS Version')),
                ('app_version', models.CharField(default='1.0.0', max_length=50, verbose_name='App Version')),
                ('is_online', models.BooleanField(default=True, verbose_name='Is Currently Online')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Device Revoked / Blocked')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Successful Sync')),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Heartbeat Received')),
                ('pending_sync_count', models.IntegerField(default=0, verbose_name='Pending Sync Queue Count')),
                ('successful_sync_count', models.IntegerField(default=0, verbose_name='Lifetime Successful Sync Items')),
                ('failed_sync_count', models.IntegerField(default=0, verbose_name='Lifetime Failed Sync Items')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to='employees.employee', verbose_name='Associated Employee')),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueueRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('client_id', models.CharField(db_index=True, max_length=100, verbose_name='Client-side UUID / Local ID')),
                ('action_type', models.CharField(choices=[('TASK_CREATE', 'Create Task'), ('TASK_UPDATE', 'Update Task Status/Details'), ('TASK_COMMENT', 'Add Task Comment'), ('ATTENDANCE_PUNCH', 'Offline Attendance Punch'), ('DAILY_REPORT', 'Submit Daily Work Report'), ('MARKETING_VISIT', 'Record Field Visit & Checklist'), ('MARKETING_LEAD', 'Create / Update Marketing Lead'), ('OPERATIONS_CHECKLIST', 'Operations Venue/Readiness Checklist'), ('IT_TICKET_NOTE', 'IT Ticket Troubleshooting Note'), ('HR_REQUEST', 'Employee HR Request'), ('GENERIC_MUTATION', 'Generic Offline Action')], max_length=50, verbose_name='Action Type')),
                ('client_timestamp', models.DateTimeField(verbose_name='Client Timestamp when action was performed offline')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Authoritative Server Reception Timestamp')),
                ('payload', models.JSONField(default=dict, verbose_name='Action Payload')),
                ('status', models.CharField(choices=[('SYNCED', 'Successfully Reconciled'), ('CONFLICT', 'Conflict Detected - Awaiting Resolution'), ('REJECTED', 'Server Authority Rejected (e.g. Tampering / Invalid Window)'), ('ERROR', 'Processing Exception')], default='SYNCED', max_length=30, verbose_name='Sync Status')),
                ('server_version', models.IntegerField(default=1, verbose_name='Server Record Version')),
                ('server_entity_id', models.CharField(blank=True, max_length=100, verbose_name='Created/Updated Server Entity ID')),
                ('conflict_details', models.JSONField(blank=True, null=True, verbose_name='Conflict Metadata')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Trace / Reason')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_records', to='sync_engine.deviceregistration')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Sync Queue Audit Record',
                'verbose_name_plural': 'Sync Queue Audit Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Entity Type (e.g. Task, Partner, Report)')),
                ('entity_id', models.CharField(max_length=100, verbose_name='Server Entity ID')),
                ('server_data', models.JSONField(default=dict, verbose_name='Current Live Server State')),
                ('client_data', models.JSONField(default=dict, verbose_name='Offline Client Submitted State')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('RESOLVED_SERVER_WINS', 'Resolved: Server Authority Kept'), ('RESOLVED_CLIENT_WINS', 'Resolved: Client Offline Update Applied'), ('RESOLVED_MERGED', 'Resolved: Merged Attributes')], default='PENDING_REVIEW', max_length=30, verbose_name='Conflict Status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Explanation / Audit Note')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolution Timestamp')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('sync_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync_engine.syncqueuerecord', verbose_name='Originating Sync Record')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'ordering': ['-created_at'],
            },
        ),
    ]
