# Generated by Django 5.1.15 on 2026-10-03 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('employee_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Employee Code')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited / Unverified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked (Failed Logins)'), ('DEACTIVATED', 'Deactivated / Offboarded')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Account Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_mfa_enabled', models.BooleanField(default=False, verbose_name='MFA Enabled')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Changed At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='MFASetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('method', models.CharField(choices=[('TOTP', 'Authenticator App (TOTP)'), ('EMAIL', 'Email Verification Code')], default='TOTP', max_length=20, verbose_name='MFA Method')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='TOTP Secret Key')),
                ('is_verified', models.BooleanField(default=False, verbose_name='MFA Verified')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used Timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Setting',
                'verbose_name_plural': 'MFA Settings',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('password_hash', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('code_hash', models.CharField(max_length=255, verbose_name='Hashed Recovery Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Code Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Code',
                'verbose_name_plural': 'Recovery Codes',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('device_id', models.CharField(db_index=True, max_length=255, verbose_name='Device Fingerprint ID')),
                ('device_name', models.CharField(max_length=150, verbose_name='Device Model/Name')),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android Phone / Tablet'), ('IOS', 'iPhone / iPad'), ('WEB', 'Web Browser'), ('OTHER', 'Other Device')], default='ANDROID', max_length=20, verbose_name='Device Type')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='OS Version')),
                ('app_version', models.CharField(blank=True, max_length=30, verbose_name='App Version')),
                ('push_token', models.TextField(blank=True, null=True, verbose_name='FCM Push Token')),
                ('is_trusted', models.BooleanField(default=True, verbose_name='Trusted Device')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked')),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Active Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_active_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='JWT JTI Token Identifier')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent String')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session Active')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Activity')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Timestamp')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.userdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
