# Generated by Django 5.1.15 on 2026-10-04 12:39

import apps.it_ops.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('component_type', models.CharField(choices=[('SERVER', 'Server / Compute'), ('API', 'API / Gateway'), ('DATABASE', 'Database'), ('APPLICATION', 'Frontend / Application'), ('DOMAIN', 'Domain / DNS'), ('SSL_CERT', 'SSL Certificate'), ('CLOUD_SERVICE', 'Cloud Service'), ('SCHEDULED_JOB', 'Scheduled / Cron Job'), ('BACKUP', 'Backup Service'), ('INTEGRATION', 'Third-Party Integration')], default='API', max_length=30)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded Performance'), ('WARNING', 'Warning / Attention'), ('DOWN', 'Major Outage / Down'), ('MAINTENANCE', 'Scheduled Maintenance')], default='OPERATIONAL', max_length=20)),
                ('endpoint_or_host', models.CharField(blank=True, max_length=255)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=99.95, max_digits=5)),
                ('last_health_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('ssl_expiry_date', models.DateField(blank=True, null=True)),
                ('responsible_team', models.CharField(default='Core Backend / DevOps', max_length=100)),
                ('dependencies_info', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Component',
                'verbose_name_plural': 'System Components',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('application', models.CharField(default='PartyBala Enterprise CRM', max_length=150)),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='STAGING', max_length=30)),
                ('version_tag', models.CharField(default='v2.8.4', max_length=50)),
                ('commit_hash', models.CharField(default='a8f9c12', max_length=40)),
                ('build_passed', models.BooleanField(default=True)),
                ('tests_passed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ROLLBACK', 'Rolled Back')], default='SUCCESS', max_length=20)),
                ('logs_output', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deployments', to='employees.employee')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_deployments', to='employees.employee')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='ITAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('request_number', models.CharField(max_length=30, unique=True)),
                ('request_type', models.CharField(choices=[('VPN', 'VPN Access'), ('DATABASE', 'Database Read/Write Access'), ('SERVER_SSH', 'Server SSH Access'), ('SOFTWARE_INSTALL', 'Licensed Software Installation'), ('CLOUD_IAM', 'Cloud / AWS / GCP IAM Role'), ('NEW_EMPLOYEE_SETUP', 'New Hire Hardware & IT Setup'), ('EMAIL', 'Email Alias / Distribution List'), ('HARDWARE_REPLACEMENT', 'Hardware Replacement / Upgrade')], default='SOFTWARE_INSTALL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IT_REVIEW', 'Under IT Review'), ('ASSIGNED', 'Assigned to Engineer'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved / Provisioned'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('provisioned_details', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_it_requests', to='employees.employee')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_it_requests', to='employees.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_it_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('asset_tag', models.CharField(default=apps.it_ops.models.generate_asset_tag, max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile Device'), ('MONITOR', 'External Monitor'), ('KEYBOARD', 'Keyboard / Peripherals'), ('ROUTER', 'Network Router / Switch'), ('SERVER', 'Rack / On-Premise Server'), ('PRINTER', 'Office Printer'), ('SOFTWARE_LICENSE', 'Software License / Seat')], default='LAPTOP', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In Use'), ('AVAILABLE', 'Available in Stock'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired / Deprecated')], default='ACTIVE', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('installed_software', models.TextField(blank=True)),
                ('maintenance_history', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hardware_assets', to='employees.employee')),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='ITIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('incident_number', models.CharField(db_index=True, default=apps.it_ops.models.generate_incident_number, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Network'), ('SERVER', 'Server'), ('DATABASE', 'Database'), ('ACCESS_REQUEST', 'Access Request'), ('EMAIL', 'Email / Communication'), ('SECURITY', 'Security'), ('APPLICATION_BUG', 'Application Bug'), ('USER_SUPPORT', 'User Support'), ('INFRASTRUCTURE', 'Infrastructure')], default='APPLICATION_BUG', max_length=30)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('impact', models.TextField(blank=True, help_text='Who or what systems are affected')),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_it_incidents', to='employees.employee')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_it_incidents', to='employees.employee')),
                ('affected_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='it_ops.systemcomponent')),
            ],
            options={
                'verbose_name': 'IT Incident / Ticket',
                'verbose_name_plural': 'IT Incidents / Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITIncidentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('comment_text', models.TextField()),
                ('is_internal_log', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='it_ops.itincident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('SOPS', 'Standard Operating Procedures'), ('TROUBLESHOOTING', 'Troubleshooting Runbook'), ('DEPLOYMENT', 'Deployment Guide'), ('DATABASE', 'Database Guide'), ('SECURITY', 'Security Procedure'), ('NETWORK', 'Network & Infrastructure'), ('API_DOCS', 'API & Architecture Documentation'), ('EMPLOYEE_GUIDES', 'General Employee IT Guide')], default='TROUBLESHOOTING', max_length=30)),
                ('summary', models.TextField()),
                ('content', models.TextField(help_text='Detailed markdown documentation or steps')),
                ('steps_checklist', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('pr_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('repository', models.CharField(default='partybala/core-platform', max_length=150)),
                ('source_branch', models.CharField(max_length=150)),
                ('target_branch', models.CharField(default='main', max_length=150)),
                ('build_status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('RUNNING', 'Running'), ('QUEUED', 'Queued')], default='RUNNING', max_length=20)),
                ('test_status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('RUNNING', 'Running'), ('QUEUED', 'Queued')], default='PASSED', max_length=20)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=20)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('MERGED', 'Merged'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
                ('summary', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_prs', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('tasks_completed_count', models.PositiveIntegerField(default=0)),
                ('bugs_fixed_count', models.PositiveIntegerField(default=0)),
                ('tickets_resolved_count', models.PositiveIntegerField(default=0)),
                ('deployments_count', models.PositiveIntegerField(default=0)),
                ('code_reviews_count', models.PositiveIntegerField(default=0)),
                ('incidents_handled', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('tomorrow_plan', models.TextField(blank=True)),
                ('summary_notes', models.TextField(blank=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_daily_reports', to='employees.employee')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('developer', 'report_date')},
            },
        ),
    ]
