# Generated by Django 5.1.15 on 2026-10-04 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0002_alter_role_code'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Actual Hours'),
        ),
        migrations.AddField(
            model_name='task',
            name='department_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Department Custom Form Fields'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_timer_running',
            field=models.BooleanField(default=False, verbose_name='Timer Currently Running'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Parent Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags / Labels'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='List of mentioned usernames/employee_codes'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='department_fields_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Project Name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Project Code')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget / Estimated Hours')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progress %')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organization.department', verbose_name='Department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='employees.employee', verbose_name='Team Members')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration in Minutes')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Work Notes')),
                ('is_running', models.BooleanField(default=True, verbose_name='Is Currently Running')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
