# Generated by Django 5.1.15 on 2026-10-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Role Code'),
        ),
    ]
