# Generated by Django 5.1.15 on 2026-10-04 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('lead_type', models.CharField(choices=[('venue', 'Venue / Banquet'), ('vendor', 'Vendor / Supplier'), ('partner', 'Corporate Partner'), ('sponsor', 'Sponsor / Event Organizer'), ('client', 'Direct Client')], default='venue', max_length=32)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(default='Kanpur', max_length=100)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit_scheduled', 'Visit Scheduled'), ('visited', 'Visited'), ('negotiation', 'In Negotiation'), ('onboarding', 'Onboarding'), ('active', 'Active / Won'), ('lost', 'Lost / Dropped')], db_index=True, default='new', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('interest_level', models.CharField(choices=[('high', 'High Interest'), ('medium', 'Medium Interest'), ('low', 'Low Interest'), ('undecided', 'Undecided')], default='undecided', max_length=20)),
                ('source', models.CharField(default='field_scouting', max_length=50)),
                ('estimated_deal_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expected_decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('activity_timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp Chat'), ('meeting', 'In-Person Meeting'), ('visit', 'Site Visit'), ('email', 'Email')], default='call', max_length=32)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=32)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='marketing.lead')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('auto_tasks_completed', models.IntegerField(default=0)),
                ('auto_visits_completed', models.IntegerField(default=0)),
                ('auto_followups_completed', models.IntegerField(default=0)),
                ('auto_leads_created', models.IntegerField(default=0)),
                ('auto_onboardings_completed', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('tomorrow_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_marketing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('target_visits', models.IntegerField(default=20)),
                ('completed_visits', models.IntegerField(default=0)),
                ('target_followups', models.IntegerField(default=50)),
                ('completed_followups', models.IntegerField(default=0)),
                ('target_leads', models.IntegerField(default=15)),
                ('completed_leads', models.IntegerField(default=0)),
                ('target_onboardings', models.IntegerField(default=5)),
                ('completed_onboardings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('venue', 'Venue / Banquet'), ('vendor', 'General Vendor'), ('caterer', 'Catering Partner'), ('decorator', 'Decorator'), ('photographer', 'Photographer / Media')], default='venue', max_length=50)),
                ('workflow_step', models.CharField(choices=[('info', '1. Partner Information'), ('documents', '2. Documents Collection'), ('kyc', '3. KYC Verification'), ('photos', '4. Property Photos'), ('amenities', '5. Amenities & Services'), ('packages', '6. Packages & Pricing'), ('manager_review', '7. Manager Review'), ('admin_approval', '8. Admin Approval'), ('active', '9. Active Live Partner')], default='info', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft / In Progress'), ('under_review', 'Submitted for Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('active', 'Active & Live'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('progress_percentage', models.IntegerField(default=10)),
                ('info_data', models.JSONField(blank=True, default=dict)),
                ('documents_data', models.JSONField(blank=True, default=dict)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('photos_data', models.JSONField(blank=True, default=list)),
                ('amenities_data', models.JSONField(blank=True, default=list)),
                ('packages_data', models.JSONField(blank=True, default=list)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_onboardings', to=settings.AUTH_USER_MODEL)),
                ('assigned_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_submissions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='marketing.lead')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('venue_onboarding', 'Venue Onboarding'), ('vendor_meeting', 'Vendor Meeting'), ('lead_followup', 'Lead Follow-up'), ('site_audit', 'Site Audit & Verification'), ('relationship', 'Relationship Management')], default='venue_onboarding', max_length=50)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], db_index=True, default='scheduled', max_length=32)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('expected_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('expected_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_checkin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_location_verified', models.BooleanField(default=True)),
                ('partner_interest', models.CharField(default='medium', max_length=20)),
                ('expected_decision_date', models.DateField(blank=True, null=True)),
                ('discussion_notes', models.TextField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_visits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='marketing.lead')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='marketing_l_status_4e3c33_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'city'], name='marketing_l_lead_ty_276905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketingdailyreport',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='marketingtarget',
            unique_together={('employee', 'month')},
        ),
    ]
