# Generated by Django 5.1.15 on 2026-10-04 05:13

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0002_alter_role_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('ticket_number', models.CharField(db_index=True, default=apps.tickets.models.generate_ticket_number, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('IT_SUPPORT', 'IT & Technical Support'), ('ASSET_REQUEST', 'Hardware / Asset Request'), ('LEAVE_REQUEST', 'Leave & Attendance Regularization'), ('PURCHASE', 'Purchase & Expense Requisition'), ('ACCOUNTS', 'Accounts & Salary Query'), ('OPERATIONS', 'Operations & Field Support'), ('GENERAL', 'General Administrative Request')], db_index=True, default='IT_SUPPORT', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_helpdesk_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Technician / Handler')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to='employees.employee', verbose_name='Requester Employee')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='organization.department', verbose_name='Target Department')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier across all systems.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('comment_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
